// Auth
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
// App
export const SET_APP_LANGUAGE = "SET_APP_LANGUAGE";

export const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";

export const SET_BREADCRUMB_KEY = "SET_BREADCRUMB_KEY"

export const SET_STORIES_LIST = "SET_STORIES_LIST"

export const SET_SERVICE_LOADER = "SET_SERVICE_LOADER"



